#!/bin/bash
echo "========================================="
echo "FILE SYSTEM PERFORMANCE COMPARISON REPORT"
echo "========================================="
echo "Generated on: $(date)"
echo ""
echo "1. MOUNT OPTIONS COMPARISON"
echo "----------------------------"
echo "EXT4 Mount Options:"
mount | grep ext4-tuned | awk '{print $6}'
echo ""
echo "XFS Mount Options:"
mount | grep xfs-tuned | awk '{print $6}'
echo ""
echo "BTRFS Mount Options:"
mount | grep btrfs-tuned | awk '{print $6}'
echo ""
echo "2. DISK USAGE COMPARISON"
echo "------------------------"
df -h | grep -E "(ext4-tuned|xfs-tuned|btrfs-tuned)"
echo ""
echo "3. FILE SYSTEM FEATURES"
echo "-----------------------"
echo "EXT4 Features:"
tune2fs -l /dev/loop1 | grep "Filesystem features"
echo ""
echo "XFS Features:"
xfs_info /mnt/xfs-tuned | head -3
echo ""
echo "BTRFS Features:"
btrfs filesystem show /dev/loop3 | head -3
echo ""
echo "4. PERFORMANCE RECOMMENDATIONS"
echo "------------------------------"
echo "Based on the tests performed:"
echo ""
echo "• EXT4: Best for general-purpose workloads with good balance of performance and stability"
echo "• XFS: Excellent for large files and high-throughput applications"
echo "• BTRFS: Good for scenarios requiring advanced features like compression and snapshots"
echo ""
echo "• noatime/nodiratime options provide significant performance improvements"
echo "• Proper I/O scheduler selection is crucial for optimal performance"
echo "• File system block size should match workload characteristics"
echo ""
echo "Report generation completed"
