#!/bin/bash
echo "=== vmstat Output Explanation ==="
echo ""

vmstat 1 1
echo ""

echo "Columns Explanation:"
echo ""
echo "Procs:"
echo " r = processes waiting for CPU"
echo " b = processes in uninterruptible sleep"
echo ""
echo "Memory:"
echo " swpd = virtual memory used (KB)"
echo " free = idle memory (KB)"
echo " buff = memory used as buffers (KB)"
echo " cache = memory used as cache (KB)"
echo ""
echo "Swap:"
echo " si = memory swapped in from disk (KB/s)"
echo " so = memory swapped out to disk (KB/s)"
echo ""
echo "IO:"
echo " bi = blocks received from block device (blocks/s)"
echo " bo = blocks sent to block device (blocks/s)"
echo ""
echo "System:"
echo " in = interrupts per second"
echo " cs = context switches per second"
echo ""
echo "CPU:"
echo " us = user time"
echo " sy = system time"
echo " id = idle time"
echo " wa = wait time"
